name = "ExtensionsTestDemo"
uuid = "616845b9-c76f-4334-a9b0-b5b1f83ddc05"
authors = ["Seth Axen <seth@sethaxen.com> and contributors"]
version = "1.10.0"

[weakdeps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"  # depens on Random

[extensions]
ExtensionsTestDemoStatsBaseExt = ["Random", "StatsBase"]

[compat]
Random = "1.10"
StatsBase = "0.34.3"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
